# Generated by Django 5.2.8 on 2025-11-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contato_atualizado_em_pedido_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='subtitulo_chamada',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
