# Generated by Django 5.2.8 on 2025-11-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pagina_subtitulo_chamada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='imagem_fundo',
            field=models.ImageField(blank=True, null=True, upload_to='fundo/'),
        ),
    ]
